### ISSUE TITLE
jira session panics

### ISSUE THREAD

**Issue by stchris** [go-jira/jira#381]
Hello,

I'm trying out this tool and following the [quickstart instructions](https://github.com/go-jira/jira#quickstart-api-token-and-keychain). Basically my `~/.jira.d/config.yml` looks like this:

```
endpoint: https://company.atlassian.net
user: <firstname.lastname@company.com>
password-source: keyring
```

Now when I run `jira session`:

```
$ jira session
The name org.freedesktop.secrets was not provided by any .service files
goroutine 1 [running]:
runtime/debug.Stack(0xc000141098, 0x96c340, 0xc00007c330)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/go-jira/jira/jiracli.HandleExit()
        /__w/jira/jira/jiracli/cli.go:46 +0x8c
panic(0x96c340, 0xc00007c330)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/go-jira/jira/jiracli.(*GlobalOptions).GetPass(0xc000116800, 0x0, 0x0)
        /__w/jira/jira/jiracli/password.go:65 +0x1d46
github.com/go-jira/jira/jiracli.register.func1(0xc000138400, 0x2, 0x9cb250, 0xa)
        /__w/jira/jira/jiracli/cli.go:172 +0xa2
github.com/coryb/oreo.(*Client).Do(0xc000133540, 0xc000138400, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/coryb/oreo@v0.0.0-20180804211640-3e1b88fc08f1/oreo.go:320 +0xcc
github.com/coryb/oreo.(*Client).GetJSON(0xc000133540, 0xc00011ab00, 0x33, 0x1, 0x1, 0xc00011ab00)
        /go/pkg/mod/github.com/coryb/oreo@v0.0.0-20180804211640-3e1b88fc08f1/oreo.go:451 +0x1a0
github.com/go-jira/jira.GetSession(0xa9ea20, 0xc000133540, 0xc0000a76e0, 0x1f, 0x0, 0x0, 0x0)
        /__w/jira/jira/session.go:58 +0xd5
github.com/go-jira/jira/jiracmd.CmdSession(0xc0001334a0, 0xc000116800, 0xc0000de6e0, 0x0, 0x0)
        /__w/jira/jira/jiracmd/session.go:31 +0x192
github.com/go-jira/jira/jiracmd.CmdSessionRegistry.func2(0xc0001334a0, 0xc000116800, 0x0, 0x3)
        /__w/jira/jira/jiracmd/session.go:23 +0x3e
github.com/go-jira/jira/jiracli.register.func4(0xc0001a61b0, 0x40c263, 0x9480e0)
        /__w/jira/jira/jiracli/cli.go:257 +0x88
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc00018b2d8, 0xc0001a61b0, 0x0, 0x0)
        /go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc00011f590, 0xc0001a61b0, 0x0, 0x0)
        /go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdc
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc00011f590, 0xc0001a61b0, 0xc0001792a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc000141bf8)
        /go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc00011f590, 0xc0000ac010, 0x1, 0x1, 0x1, 0xc0001a6120, 0x0, 0x0)
        /go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fe
github.com/go-jira/jira/jiracli.ParseCommandLine(0xc00011f590, 0xc0000ac010, 0x1, 0x1)
        /__w/jira/jira/jiracli/usage.go:187 +0xee
main.main()
        /__w/jira/jira/cmd/jira/main.go:53 +0x540
```

```
$ jira version
v1.0.26

$ uname -a
Linux hostname 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

Thanks for looking into this!

**Comment by paoloantinori** [comment]
I see the same exact error on Fedora.
